HW-1, HashMap
egor-bogomolov/spbau-java-hw pull request #1
Opened 2016-09-20 14:07 UTC by egor-bogomolov

HW-1, HashMap

2016-09-27 16:32 UTC, sproshev requested changes
Надо исправлять

2016-09-27 16:32 UTC, sproshev commented on Task1/.idea/vcs.xml
> +</project>
папку .idea без явных причин коммитить не надо

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> +        return hashMap[hash % hashMap.length].contains(hash);
кусок

```
        int hash = key.hashCode();
        if (hash < 0) {
            hash *= -1;
        }
        ...hashMap[hash % hashMap.length]...
```

повторяется несколько раз, его стоит выделить в отдельный метод

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> +            hash *= -1;
запусти

```
public class Main {
    public static void main(String[] args) {
        System.out.println(Integer.MIN_VALUE * -1);;
    }
}
```

))

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> +        size++;
а если по ключу уже что-то хранилось? -1

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> +    public String remove(String string) {
лучше называть параметры более осмысленно

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> +        }
зачем так сложно? зануляем все элементы внутри hashMap и всё

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> +    }
у разных ключей хеш-код может совпасть, в таком случае таблица может повести себя некорректно. -1

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> +    private class Node {
static

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> +                result = node.stored.value;
может тут сразу return можно сделать?

2016-09-27 16:32 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> +        return result;
теперь хранится и старое и новое значение по ключу? -1

2016-09-27 16:32 UTC, sproshev commented on Task1/src/test/java/ru/spbau/bogomolov/MyHashMapTest.java
> +            assertEquals(true, hashMap.contains(s));
assertTrue

2016-09-27 16:32 UTC, sproshev commented on Task1/src/test/java/ru/spbau/bogomolov/MyHashMapTest.java
> +            assertNotEquals(null, hashMap.remove(s));
assertNotNull

2016-09-27 16:32 UTC, sproshev commented on Task1/src/test/java/ru/spbau/bogomolov/MyHashMapTest.java
> +            assertEquals(null, hashMap.remove(s));
assertNull

2016-12-21 17:43 UTC, egor-bogomolov commented
Исправил ошибки.

On Tue, Sep 27, 2016 at 7:32 PM, Semyon Proshev <notifications@github.com>
wrote:

> *@sproshev* requested changes on this pull request.
>
> Надо исправлять
> ------------------------------
>
> In Task1/.idea/vcs.xml
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > @@ -0,0 +1,6 @@
> +<?xml version="1.0" encoding="UTF-8"?>
> +<project version="4">
> +  <component name="VcsDirectoryMappings">
> +    <mapping directory="$PROJECT_DIR$/.." vcs="Git" />
> +  </component>
> +</project>
>
> папку .idea без явных причин коммитить не надо
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +        hashMap = new MyList[START_SIZE];
> +        for (int i = 0; i < START_SIZE; i++) {
> +            hashMap[i] = new MyList();
> +        }
> +    }
> +
> +    public int size() {
> +        return size;
> +    }
> +
> +    public boolean contains(String key) {
> +        int hash = key.hashCode();
> +        if (hash < 0) {
> +            hash *= -1;
> +        }
> +        return hashMap[hash % hashMap.length].contains(hash);
>
> кусок
>
>         int hash = key.hashCode();
>         if (hash < 0) {
>             hash *= -1;
>         }
>         ...hashMap[hash % hashMap.length]...
>
> повторяется несколько раз, его стоит выделить в отдельный метод
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +    public MyHashMap() {
> +        size = 0;
> +        hashMap = new MyList[START_SIZE];
> +        for (int i = 0; i < START_SIZE; i++) {
> +            hashMap[i] = new MyList();
> +        }
> +    }
> +
> +    public int size() {
> +        return size;
> +    }
> +
> +    public boolean contains(String key) {
> +        int hash = key.hashCode();
> +        if (hash < 0) {
> +            hash *= -1;
>
> запусти
>
> public class Main {
>     public static void main(String[] args) {
>         System.out.println(Integer.MIN_VALUE * -1);;
>     }
> }
>
> ))
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +        return hashMap[hash % hashMap.length].contains(hash);
> +    }
> +
> +    public String get(String key) {
> +        int hash = key.hashCode();
> +        if (hash < 0) {
> +            hash *= -1;
> +        }
> +        return hashMap[hash % hashMap.length].get(hash);
> +    }
> +
> +    public String put(String key, String value) {
> +        if (size == hashMap.length) {
> +            extend();
> +        }
> +        size++;
>
> а если по ключу уже что-то хранилось? -1
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +        return hashMap[hash % hashMap.length].get(hash);
> +    }
> +
> +    public String put(String key, String value) {
> +        if (size == hashMap.length) {
> +            extend();
> +        }
> +        size++;
> +        int hash = key.hashCode();
> +        if (hash < 0) {
> +            hash *= -1;
> +        }
> +        return hashMap[hash % hashMap.length].put(hash, value);
> +    }
> +
> +    public String remove(String string) {
>
> лучше называть параметры более осмысленно
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +        if (hash < 0) {
> +            hash *= -1;
> +        }
> +        String result = hashMap[hash % hashMap.length].remove(hash);
> +        if (result != null) {
> +            size--;
> +        }
> +        return result;
> +    }
> +
> +    public void clear() {
> +        for (int i = 0; i < hashMap.length; i++) {
> +            while(!hashMap[i].empty()) {
> +                hashMap[i].removeHead();
> +            }
> +        }
>
> зачем так сложно? зануляем все элементы внутри hashMap и всё
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyHashMap.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +
> +    public boolean contains(String key) {
> +        int hash = key.hashCode();
> +        if (hash < 0) {
> +            hash *= -1;
> +        }
> +        return hashMap[hash % hashMap.length].contains(hash);
> +    }
> +
> +    public String get(String key) {
> +        int hash = key.hashCode();
> +        if (hash < 0) {
> +            hash *= -1;
> +        }
> +        return hashMap[hash % hashMap.length].get(hash);
> +    }
>
> у разных ключей хеш-код может совпасть, в таком случае таблица может
> повести себя некорректно. -1
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > @@ -0,0 +1,91 @@
> +package ru.spbau.bogomolov;
> +
> +/**
> + * Created by Egor Bogomolov on 9/19/16.
> + */
> +
> +public class MyList {
> +    private class Node {
>
> static
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +    }
> +
> +    private Node head;
> +    private int size;
> +
> +    public MyList() {
> +        head = new Node();
> +        size = 0;
> +    }
> +
> +    public String get(int key) {
> +        String result = null;
> +        Node node = head;
> +        while(node.next != node) {
> +            if (node.stored.key == key) {
> +                result = node.stored.value;
>
> может тут сразу return можно сделать?
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +        while(node.next != node) {
> +            if (node.stored.key == key) {
> +                result = node.stored.value;
> +            }
> +            node = node.next;
> +        }
> +        return result;
> +    }
> +
> +    public String put(int key, String value) {
> +        String result = get(key);
> +        Node node = new Node(key, value);
> +        node.next = head;
> +        head = node;
> +        size++;
> +        return result;
>
> теперь хранится и старое и новое значение по ключу? -1
> ------------------------------
>
> In Task1/src/test/java/ru/spbau/bogomolov/MyHashMapTest.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +import org.junit.Test;
> +
> +import static org.junit.Assert.*;
> +
> +/**
> + * Created by Egor Bogomolov on 9/19/16.
> + */
> +
> +public class MyHashMapTest {
> +    @Test
> +    public void put() throws Exception {
> +        MyHashMap hashMap = new MyHashMap();
> +        String s = "";
> +        for (int i = 0; i < 1000; i++) {
> +            hashMap.put(s, s);
> +            assertEquals(true, hashMap.contains(s));
>
> assertTrue
> ------------------------------
>
> In Task1/src/test/java/ru/spbau/bogomolov/MyHashMapTest.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-1767490>
> :
>
> > +            assertEquals(false, hashMap.contains(s));
> +            s += 'a';
> +        }
> +    }
> +
> +    @Test
> +    public void removeAfterAllPuts() throws Exception {
> +        MyHashMap hashMap = new MyHashMap();
> +        String s = "";
> +        for (int i = 0; i < 1000; i++) {
> +            hashMap.put(s, s);
> +            s += 'a';
> +        }
> +        s = "";
> +        for (int i = 0; i < 1000; i++) {
> +            assertNotEquals(null, hashMap.r [...]

2016-12-24 19:51 UTC, sproshev approved these changes
6. ровно зачет)

2016-12-24 19:51 UTC, sproshev commented on Task1/.idea/vcs.xml
> +</project>
не изменилось -1

2016-12-24 19:51 UTC, sproshev commented on Task1/build.gradle
> +sourceCompatibility = 1.5
1.8

2016-12-24 19:51 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> +        while(node.next != node) {
кстати, можно было `node.next != node` выделить в метод, чтобы легче читалось и чуть что было проще заменить определение того, является ли элемент последним

2016-12-24 19:51 UTC, sproshev commented on Task1/src/main/java/ru/spbau/bogomolov/PairKeyValue.java
> +    public String key;
final

2016-12-24 19:51 UTC, sproshev commented on Task1/src/test/java/ru/spbau/bogomolov/MyHashMapTest.java
> +            assertTrue(s.equals(hashMap.get(s)));
`assertEquals(s, hM.get(s))`

2016-12-25 02:53 UTC, egor-bogomolov commented
А из идеи можно убирать файлы/папки из гита? Я умею это делать из консоли,
а как это делать внутри идеи я не нашел.

On Dec 24, 2016 10:51 PM, "Semyon Proshev" <notifications@github.com> wrote:

> *@sproshev* approved this pull request.
>
>    1. ровно зачет)
>
> ------------------------------
>
> In Task1/.idea/vcs.xml
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-14356686>
> :
>
> > @@ -0,0 +1,6 @@
> +<?xml version="1.0" encoding="UTF-8"?>
> +<project version="4">
> +  <component name="VcsDirectoryMappings">
> +    <mapping directory="$PROJECT_DIR$/.." vcs="Git" />
> +  </component>
> +</project>
>
> не изменилось -1
> ------------------------------
>
> In Task1/build.gradle
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-14356686>
> :
>
> > @@ -0,0 +1,14 @@
> +group 'ru.spbau.bogomolov'
> +version '1.0-SNAPSHOT'
> +
> +apply plugin: 'java'
> +
> +sourceCompatibility = 1.5
>
> 1.8
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/MyList.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-14356686>
> :
>
> > +            stored = new PairKeyValue(key, value);
> +            next = this;
> +        }
> +    }
> +
> +    private Node head;
> +    private int size;
> +
> +    public MyList() {
> +        head = new Node();
> +        size = 0;
> +    }
> +
> +    public String get(String key) {
> +        Node node = head;
> +        while(node.next != node) {
>
> кстати, можно было node.next != node выделить в метод, чтобы легче
> читалось и чуть что было проще заменить определение того, является ли
> элемент последним
> ------------------------------
>
> In Task1/src/main/java/ru/spbau/bogomolov/PairKeyValue.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-14356686>
> :
>
> > @@ -0,0 +1,34 @@
> +package ru.spbau.bogomolov;
> +
> +/**
> + * Created by Egor Bogomolov on 9/19/16.
> + */
> +
> +public class PairKeyValue {
> +    public String key;
>
> final
> ------------------------------
>
> In Task1/src/test/java/ru/spbau/bogomolov/MyHashMapTest.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-14356686>
> :
>
> > +    public void removeFromEmpty() throws Exception {
> +        MyHashMap hashMap = new MyHashMap();
> +        String s = "";
> +        for (int i = 0; i < 10; i++) {
> +            assertNull(hashMap.remove(s));
> +            s += 'a';
> +        }
> +    }
> +
> +    @Test
> +    public void get() throws Exception {
> +        MyHashMap hashMap = new MyHashMap();
> +        String s = "";
> +        for (int i = 0; i < 10; i++) {
> +            hashMap.put(s, s);
> +            assertTrue(s.equals(hashMap.get(s)));
>
> assertEquals(s, hM.get(s))
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/1#pullrequestreview-14356686>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQ93h9j1RlfZA1S2slbiX5jQ6tJprEsXks5rLXe8gaJpZM4KBq02>
> .
>

2016-12-25 15:19 UTC, sproshev commented
я тоже не встречал

2018-02-17 11:28 UTC, merged