PR: Java02. ДЗ 03, Богомолов Егор
egor-bogomolov/spbau-java-hw pull request #4
Opened 2016-10-25 19:15 UTC by egor-bogomolov

hw-3

2016-10-29 16:57 UTC, sproshev commented
еще папку gradle/wrapper надо добавить, иначе проект не открывается

2016-10-29 18:02 UTC, egor-bogomolov commented
Добавил

On Sat, Oct 29, 2016 at 7:57 PM, Semyon Proshev <notifications@github.com>
wrote:

> еще папку gradle/wrapper надо добавить, иначе проект не открывается
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#issuecomment-257102740>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQ93hyqBldTHyKvm9-jZ433YDli-8wkkks5q43sAgaJpZM4KgX8q>
> .
>

2016-10-29 18:24 UTC, sproshev requested changes
надо исправлять

2016-10-29 18:24 UTC, sproshev commented on Task1/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
а вот это лишнее

2016-10-29 18:24 UTC, sproshev commented on Task3/src/main/java/ru/spbau/bogomolov/Collections.java
> +    private static <T, R> R recursive_foldr(Function2<? super T, ? super R, ? extends R> function,
подчеркивания в джаве не используются -0.5
только в константах

2016-10-29 18:24 UTC, sproshev commented on Task3/src/test/java/ru/spbau/bogomolov/CollectionsTest.java
> +        letters = new ArrayList<>(Arrays.asList("a", "b", "c", "d", "e", "f"));
letters = Arrays.asList("a", "b", "c", "d", "e", "f");

2016-10-29 18:24 UTC, sproshev commented on Task3/src/test/java/ru/spbau/bogomolov/CollectionsTest.java
> +
у правой и левой сверток должны быть разные результаты

2016-10-29 18:24 UTC, sproshev commented on Task3/src/test/java/ru/spbau/bogomolov/CollectionsTest.java
> +}
не проверяются wildcard'ы

2016-10-29 18:24 UTC, sproshev commented on Task3/src/test/java/ru/spbau/bogomolov/PredicateTest.java
> +}
не проверяется ленивость

2016-11-12 18:05 UTC, egor-bogomolov commented
Забыл отправить сообщение о том, что я внес исправления. Так вот, я внес
исправления.

On Sat, Oct 29, 2016 at 9:24 PM, Semyon Proshev <notifications@github.com>
wrote:

> *@sproshev* requested changes on this pull request.
>
> надо исправлять
> ------------------------------
>
> In Task1/.idea/workspace.xml
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#pullrequestreview-6351793>
> :
>
> > @@ -0,0 +1,773 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> а вот это лишнее
> ------------------------------
>
> In Task3/src/main/java/ru/spbau/bogomolov/Collections.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#pullrequestreview-6351793>
> :
>
> > +    public static <T> List<T> takeWhile(Predicate<? super T> predicate, Iterable<T> iterable) {
> +        List<T> list = new ArrayList<T>();
> +        for (T element : iterable) {
> +            if (!predicate.apply(element)) {
> +                break;
> +            }
> +            list.add(element);
> +        }
> +        return list;
> +    }
> +
> +    public static <T> List<T> takeUnless(Predicate<? super T> predicate, Iterable<T> iterable) {
> +        return takeWhile(predicate.not(), iterable);
> +    }
> +
> +    private static <T, R> R recursive_foldr(Function2<? super T, ? super R, ? extends R> function,
>
> подчеркивания в джаве не используются -0.5
> только в константах
> ------------------------------
>
> In Task3/src/test/java/ru/spbau/bogomolov/CollectionsTest.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#pullrequestreview-6351793>
> :
>
> > +import static org.junit.Assert.*;
> +
> +public class CollectionsTest {
> +    private List<Integer> array;
> +    private List<Integer> onlyEven;
> +    private List<Integer> less50;
> +    private List<Integer> mod3;
> +    private List<String> letters;
> +
> +    @Before
> +    public void init() {
> +        array = new ArrayList<>();
> +        onlyEven = new ArrayList<>();
> +        less50 = new ArrayList<>();
> +        mod3 = new ArrayList<>();
> +        letters = new ArrayList<>(Arrays.asList("a", "b", "c", "d", "e", "f"));
>
> letters = Arrays.asList("a", "b", "c", "d", "e", "f");
> ------------------------------
>
> In Task3/src/test/java/ru/spbau/bogomolov/CollectionsTest.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#pullrequestreview-6351793>
> :
>
> > +        Predicate<Integer> pred = x -> x >= 50;
> +        assertEquals(less50, Collections.takeUnless(pred, array));
> +    }
> +
> +    @Test
> +    public void foldr() throws Exception {
> +        Function2<String, String, String> concat = (s, t) -> s + t;
> +        assertEquals("abcdef", Collections.foldr(concat, "", letters));
> +    }
> +
> +    @Test
> +    public void foldl() throws Exception {
> +        Function2<String, String, String> concat = (s, t) -> s + t;
> +        assertEquals("abcdef", Collections.foldl(concat, "", letters));
> +    }
> +
>
> у правой и левой сверток должны быть разные результаты
> ------------------------------
>
> In Task3/src/test/java/ru/spbau/bogomolov/CollectionsTest.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#pullrequestreview-6351793>
> :
>
> > +        assertEquals(less50, Collections.takeUnless(pred, array));
> +    }
> +
> +    @Test
> +    public void foldr() throws Exception {
> +        Function2<String, String, String> concat = (s, t) -> s + t;
> +        assertEquals("abcdef", Collections.foldr(concat, "", letters));
> +    }
> +
> +    @Test
> +    public void foldl() throws Exception {
> +        Function2<String, String, String> concat = (s, t) -> s + t;
> +        assertEquals("abcdef", Collections.foldl(concat, "", letters));
> +    }
> +
> +}
>
> не проверяются wildcard'ы
> ------------------------------
>
> In Task3/src/test/java/ru/spbau/bogomolov/PredicateTest.java
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#pullrequestreview-6351793>
> :
>
> > +        for (int x = 0; x <= 200; x++) {
> +            assertEquals((x % 2 == 0) || (x % 3 == 0), pred.apply(x));
> +        }
> +    }
> +
> +    @Test
> +    public void not() throws Exception {
> +        Predicate<Integer> pred2 = x -> (x % 2 == 0);
> +        Predicate<Integer> pred3 = x -> (x % 3 == 0);
> +        Predicate<Integer> pred = pred2.and(pred3).not();
> +        for (int x = 0; x <= 200; x++) {
> +            assertEquals(!((x % 2 == 0) && (x % 3 == 0)), pred.apply(x));
> +        }
> +    }
> +
> +}
>
> не проверяется ленивость
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/egor-bogomolov/spbau-java-hw/pull/4#pullrequestreview-6351793>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQ93h7UOvKATMfQXIFomcIn_qIgbnk4Pks5q449hgaJpZM4KgX8q>
> .
>

2016-11-12 19:53 UTC, sproshev commented on Task3/src/test/java/ru/spbau/bogomolov/CollectionsTest.java
> +}
теперь проверяются, но не везде (

2016-11-12 19:53 UTC, sproshev commented
10

2016-11-18 15:07 UTC, merged