Implemented "VCS" task
egor-bogomolov/spbau-java-hw pull request #7
Opened 2017-03-23 01:25 UTC by egor-bogomolov

HW-2, VCS

2017-03-30 12:37 UTC, jzuken requested changes

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/Application/Main.java
> +    private static String[] arguments = {"init", "add", "branch", "merge", "commit", "remove_repository",
ну то есть у нас есть вот этот массив, потом есть вывод хелпа, потом сравнение при вводе команд ниже, и если хотя бы в одном месте опечататься, получим много веселья. давайте лучше какой-нибудь enum для этого заиспользуем со всякими toString() и т.п.

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/Application/Main.java
> +        for (String arg : arguments) {
поиск значения в списке для слабых?

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/Application/Main.java
> +        if (args[0].equals("init")) {
раз у вас такая развесистая обработка каждой команды, предлагаю сделать по отдельной функции для каждой команды. а то ну совсем этот main() нечитаем получается

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/Application/Main.java
> +package Application;
по условию требовалось краткое описание внутреннего устройства, не нашёл его тут.
-0.5

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +    private List<Branch> branches;
давайте его сразу и проинициализируем, чего уж

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +        Files.createDirectory(path.resolve(Constants.myGitDirectory));
так может эти константы все в этот класс перетащить тогда?

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +                            System.out.println("Something went wrong during reading from file " + p.toString());
эх, специально ж написал в условии, обработка ошибок и вывод в консоль только в клиентском коде типа main(). а если пользователь консоль видит в принципе, как он про эту ошибку узнает? тут же даже исключение дальше не пробрасывается 
-0.5

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +        StringBuilder file = new StringBuilder();
конкатенация строк нынче использует внутри StringBuilder, так что явно его использовать необязательно

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +    private Branch getHEADBranch() throws IOException, HeadFileIsBrokenException {
ну это как-то не по стайлгайду название совсем

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +            System.out.println("commit : " + commit.getHash());
ну и тут та же история, а если мы GUI решим сделать к этой библиотеке? log() должен возвращать строку, а клиентский код уже сам решит, как и куда её вывести

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +        return (Branch) readFromHEAD(0);
и как понять, что эти 0 и 1 значат? заведите enum лучше

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/Tree.java
> +        } else if (path.getNameCount() == 1) {
а тут else можно не писать, после throw всё равно ничего больше выполняться не будет

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/Tree.java
> +    Tree addPathToTree(@NotNull Path path, @NotNull String hash) throws IOException {
а вот этот метод имеет пакетную видимость, ему бы не помешала документация

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/MyGitObject.java
> +    String BLOB = "blob";
что, прям даже не константа, а просто публичное поле?

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/MyGitObject.java
> +interface MyGitObject extends Serializable {
содержимому интерфейсов по определению нужна доументация

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/MyGitObject.java
> +            return null;
ага, вот только возвращаемое значение метода объявлено как NotNull

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/Branch.java
> +    String getName() {
вы в наследниках сознательно сужаете область видимости?

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/test/java/MyGitLibrary/MyGitObjects/RepositoryManagerTest.java
> +    public void createBranchCheckoutAddSomeFilesCheckoutBackDeleteThemAndReturnWithMerge() throws Exception {
для тестов, которые реализуют сценарии, не стоит такие имена делать -- сценарии могут быть сложные, и всё в название не закодируешь. лучше написать имя попроще, а рядом в комментарии написать уже нормально, что проверяется

2017-03-30 12:37 UTC, jzuken commented on MyGit/src/test/java/MyGitLibrary/MyGitObjects/RepositoryManagerTest.java
> +public class RepositoryManagerTest {
ок, RepositoryManager проверили. но надо бы и остальные классы проверить. модульные тесты писать поучиться и всё такое

2017-03-30 12:37 UTC, jzuken commented on MyGit/build.gradle
> +group 'ru.spbau.bogomolov'
как с таким конфигом собрать standalone jar-файл со всеми зависимостями?

2017-04-06 09:50 UTC, egor-bogomolov commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/MyGitObject.java
> +    String BLOB = "blob";
Это же интерфейс, в нем все поля "public static final", т.е. константы.

2017-04-06 09:55 UTC, egor-bogomolov commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/Branch.java
> +    String getName() {
Я сознательно оставляю ее минимальной возможной. Для перезаписываемых методов не-public поставить нельзя, а вот тут можно. А public здесь не нужен, кроме как для поддержания единообразия.
С другой стороны, поскольку у всего класса область видимости уже ограничена, можно и не пренебрегать единообразием.
Поэтому хочется спросить, что принято делать в данном случае?

2017-04-06 11:45 UTC, egor-bogomolov commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +        Files.createDirectory(path.resolve(Constants.myGitDirectory));
Но это же уже не константы, а пути, зависимые от директории, в которой инициализировали гит. Почему они должны лежать в константах?

2017-04-06 11:46 UTC, egor-bogomolov commented on MyGit/build.gradle
> +group 'ru.spbau.bogomolov'
Исправлено, как собирать описано в readme

2017-04-06 11:46 UTC, egor-bogomolov commented on MyGit/src/main/java/Application/Main.java
> +package Application;
Добавлено в readme

2017-04-16 06:40 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +        Files.createDirectory(path.resolve(Constants.myGitDirectory));
как не константы? `public static final Path myGitDirectory`, насколько я вижу. мой вопрос в том, почему они лежат где-то в стороннем месте, а не внутри репозитория, которому они нужны

2017-04-16 06:41 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/MyGitObject.java
> +    String BLOB = "blob";
виноват, не заметил

2017-04-16 06:45 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/Branch.java
> +    String getName() {
так а сам класс package-local, поэтому будут его поля публичные или тоже пакетные, уже не так важно. но, в принципе, подход нормальный

2017-04-16 06:57 UTC, jzuken requested changes

2017-04-16 06:57 UTC, jzuken commented on MyGit/src/main/java/Application/Main.java
> +            System.exit(0);
вот exit'ом бы не стоит привыкать пользоваться, он как goto, попахивает немного

2017-04-16 06:57 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/MyGitObject.java
> +     * @throws IOException - thrown if something went wrong during input or output.
а клиенту что прикажете делать? сидеть смотреть на стек вызовов и гадать, что же пошло не так? такого рода ошибки надо ловить на уровне вашей логики и перебрасывать дальше какие-то осмысленные исключения

2017-04-16 06:57 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +                            RuntimeException runtimeException = new RuntimeException(
ага, а тут из-за того, что из лямбды нельзя бросить checked исключение, вы заставляете клиентов ловить unchecked исключения. сделайте нормальный цикл тогда, не надо над клиентами издеваться за их же счёт

2017-04-16 06:57 UTC, jzuken commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/Tree.java
> +        } else {
после return'а else можно не писать и сэкономить отступ

2017-04-16 06:57 UTC, jzuken commented on MyGit/src/test/java/MyGitLibrary/MyGitObjects/RepositoryManagerTest.java
> +public class RepositoryManagerTest {
всё ещё хочу модульных тестов :)

2017-04-17 11:47 UTC, egor-bogomolov commented on MyGit/src/main/java/MyGitLibrary/MyGitObjects/RepositoryManager.java
> +        Files.createDirectory(path.resolve(Constants.myGitDirectory));
А, я не понял, что подразумевается под "этим" классом. Мотивация в том, что они используются и в других классах тоже - в Tree, в MyGitObject.

2018-02-17 11:30 UTC, merged